# Generated by Django 4.1.7 on 2023-03-08 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StoredFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('original_filename', models.CharField(max_length=2048)),
                ('url', models.URLField()),
                ('path', models.CharField(max_length=2048)),
            ],
        ),
    ]
