# Generated by Django 4.1.7 on 2023-03-13 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proxy', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='storedfile',
            name='original_filename',
            field=models.CharField(max_length=2048, unique=True),
        ),
        migrations.AlterField(
            model_name='storedfile',
            name='path',
            field=models.CharField(max_length=2048, unique=True),
        ),
        migrations.AlterField(
            model_name='storedfile',
            name='url',
            field=models.URLField(unique=True),
        ),
    ]
